// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv12b6zsiiC9fiINhEQEct9QF8fHptcKA',
    appId: '1:661911889948:web:b3095c769487314dbd17d9',
    messagingSenderId: '661911889948',
    projectId: 'mobile-payment-app-1234',
    authDomain: 'mobile-payment-app-1234.firebaseapp.com',
    storageBucket: 'mobile-payment-app-1234.appspot.com',
    measurementId: 'G-JEZ8GDFWFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCLpcapLs4yiOtvjQgdx4TP8knoZuk8Bk',
    appId: '1:661911889948:android:285db7c69aab21d3bd17d9',
    messagingSenderId: '661911889948',
    projectId: 'mobile-payment-app-1234',
    storageBucket: 'mobile-payment-app-1234.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc8RDLlnAaAwEZr2VGOm2-Av1_U2whd-c',
    appId: '1:661911889948:ios:5b8988ecf9972a89bd17d9',
    messagingSenderId: '661911889948',
    projectId: 'mobile-payment-app-1234',
    storageBucket: 'mobile-payment-app-1234.appspot.com',
    iosClientId: '661911889948-k6al6el7tt2ncpj9dttdhvrf1e3q9kiv.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobilePaymentApp',
  );
}
